#!/bin/bash
####################################################################################################################
#
# The script for incrementing build version and making new release using git-flow
#

# Version bump
CUR_VERSION=`cat $PWD/VERSION`
VERSION=`cut -d '.' -f 1,2 $PWD/VERSION`
BUILD=`cut -d '.' -f 3 $PWD/VERSION`
((BUILD=BUILD+1))
BUILD_VERSION=$VERSION.$BUILD

# If need to update version in README file
#sed -r 's/^#### Version .*/#### Version '$BUILD_VERSION'/g' $PWD/README.md > $PWD/README.md

# If need to update version data in PHP-scripts
#sed -r 's/^ \* Version: .*/ \* Version: '$BUILD_VERSION'/g' $PWD/path-to/script.php > $PWD/path-to/script.php

export GIT_MERGE_AUTOEDIT=no

git checkout -- .
git flow release start $BUILD_VERSION
echo $BUILD_VERSION > $PWD/VERSION
git commit -am "`echo 'Release version '$BUILD_VERSION`"
git flow release finish -n $BUILD_VERSION

exit 0